#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

branches:
  # whitelist
  only:
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf true

# fetch repository as zip archive. default is "false"
#shallow_clone: true

# set clone depth
clone_depth: 3

# environment variables
environment:
  MINGW_DIR: C:\CPP\compiler\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin

# scripts that run after cloning repository
install:
  # begin prepare for simulate local dev environment
  - mkdir C:\CPP
  - mkdir C:\CPP\compiler
  - mkdir C:\CPP\tools
  - move C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0 C:\CPP\compiler
  - move C:\msys64 C:\CPP\tools
  - set PATH=%MINGW_DIR%;%PATH%
  # end prepare for sim local env
  - mkdir build
  - cd build
  - cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
  - cmake --build .
  - cd test
  - ctest


#---------------------------------#
#       build configuration       #
#---------------------------------#

# to disable automatic builds
build: off