#ifndef __C_wxPanelProperties__
#define __C_wxPanelProperties__

/**
@file
Subclass of property_panel, which is generated by wxFormBuilder.
*/

#include "C_Settings.h"
#include "appl_data.h"
#include "C_wxProperties.h"

//// end generated include

/** Implementing property_panel */
class C_wxPanelProperties : public property_panel
{
    public:
        /** Constructor */
        C_wxPanelProperties( wxWindow* parent);
    //// end generated class members

        void set_settings(C_Settings* settings, ApplicationData* appl_data);
        bool SetFont(const wxFont &font);

    protected:
        void OnPropertyGridChanged(wxPropertyGridEvent& event);

    private:
        struct PropertyLine
        {
            wxString m_label;
            wxPGProperty *p_wxPGProperty_Parent;
            wxPGProperty *p_wxPGProperty;
        };

        C_Settings *s;
        ApplicationData *ad;

        std::vector<PropertyLine> m_Properties;

        void prepare_properties(void);
        void add_properties(void);

        static const wxString CATEGORY_GENERAL;
        static const wxString LAST_USED_DB;
        static const wxString USE_NEW_NUMBERING;
        static const wxString USE_TILE_TOOLTIP;
        static const wxString TERRITORY_DIMENSION;
        static const wxString MINLNG;
        static const wxString MINLAT;
        static const wxString MAXLNG;
        static const wxString MAXLAT;
        static const wxString OSM_SERVICE_URL;
        static const wxString DEL_TEMP_FILES;
        static const wxString TEMP_FILES_MAPERITIVE;
        static const wxString TEMP_FILES_IMAGEMAGICK;
        static const wxString TEMP_FILES_LATEX;
        static const wxString PDF_VIEWER;
        static const wxString FADE_ASSIGNEE_TERRITORIES_MONTHS;

        static const wxString CATEGORY_APPEARANCE;
        static const wxString FONT;
        static const wxString TILE;
        static const wxString TILE_LENGTH;
        static const wxString TILE_HEIGHT;
        static const wxString SASH_SIZE;

        static const wxString CATEGORY_TILE_COLOUR;
        static const wxString CATEGORY_ASSIGNED;
        static const wxString TILE_ASS_COLOUR_1;
        static const wxString TILE_ASS_DAYS_1;
        static const wxString TILE_ASS_COLOUR_2;
        static const wxString TILE_ASS_DAYS_2;
        static const wxString TILE_ASS_COLOUR_3;
        static const wxString TILE_ASS_DAYS_3;
        static const wxString TILE_ASS_COLOUR_4;
        static const wxString TILE_ASS_DAYS_4;
        static const wxString TILE_ASS_COLOUR_5;
        static const wxString CATEGORY_UNASSIGNED;
        static const wxString TILE_UNASS_COLOUR_1;
        static const wxString TILE_UNASS_DAYS_1;
        static const wxString TILE_UNASS_COLOUR_2;
        static const wxString TILE_UNASS_DAYS_2;
        static const wxString TILE_UNASS_COLOUR_3;
        static const wxString TILE_UNASS_DAYS_3;
        static const wxString TILE_UNASS_COLOUR_4;
        static const wxString TILE_UNASS_DAYS_4;
        static const wxString TILE_UNASS_COLOUR_5;

        static const wxString CATEGORY_PATHS;
        static const wxString MAPERITIVE_GUI;
        static const wxString MAPERITIVE_CONSOLE;
        static const wxString IMAGEMAGICK_MAGICK;
        static const wxString LATEX_BIN_DIR;

        static const wxString CATEGORY_MAPS;
        static const wxString PATH_MRULES;
        static const wxString PATH_BORDERS;
        static const wxString OSM_FILE;
        static const wxString CREATION_SIZE;
        static const wxString CREATION_WIDTH;
        static const wxString CREATION_HEIGHT;
        static const wxString CREATION_DPI;
        static const wxString PRINT_SIZE;
        static const wxString PRINT_WIDTH;
        static const wxString PRINT_HEIGHT;
};

#endif // __C_wxPanelProperties__
