#ifndef __C_wxPanelActions__
#define __C_wxPanelActions__

/**
@file
Subclass of C_wxActions, which is generated by wxFormBuilder.
*/

#include "C_wxActions.h"
#include "C_DbHandle.h"
#include "appl_data.h"
#include "C_wxScrolledWindowCat.h"
#include "safe_wx_str.h"

wxDECLARE_EVENT(EVT_ELEMENT_UPDATED, MyFooEvent);

/** Implementing C_wxActions */
class C_wxPanelActions : public C_wxActions, C_DbHandle
{
    public:
        /** Constructor */
        C_wxPanelActions( wxWindow* parent );

        void set_data(const ApplicationData *ad);
        void prepare_actions(const C_wxScrolledWindowCat::Element el);
        bool SetFont(const wxFont &font);

    private:
        const ApplicationData *ad;
        C_wxScrolledWindowCat::Element el;

        void populate_names(void);
        void populate_history(int geb_id);

        void do_assign(void);
        void do_unassign(void);
        void do_transfer(void);
        void do_processed(void);
        void do_processed_unassign(void);

        void post_element_updated(void);

        //(*Handlers(C_wxPanelActions)
        void OnBtnAssignClick(wxCommandEvent& event);
        void OnBtnUnassignClick(wxCommandEvent& event);
        void OnBtnTransferClick(wxCommandEvent& event);
        void OnBtnProcessedClick(wxCommandEvent& event);
        void OnBtnProcessedUnassignClick(wxCommandEvent& event);
        void OnBtnCommentCLR( wxCommandEvent& event );
        void OnBtnCommentGDM( wxCommandEvent& event );
        void OnBtnCommentRKG( wxCommandEvent& event );

        //*)
};

#endif // __C_wxPanelActions__
