#ifndef __C_wxTmgrMainFrame__
#define __C_wxTmgrMainFrame__

/**
@file
Subclass of C_wxTmgr, which is generated by wxFormBuilder.
*/

// workaround for a boost bug..
#ifndef __kernel_entry
#define __kernel_entry
#endif

#include <boost/process.hpp>

#include <wx/filedlg.h>

#include "helpers.h"
#include "C_wxTmgr.h"
#include "C_wxTmgrMainFrameManager.h"
#include "C_wxDlgInfo.h"
#include "C_wxScrolledImageComponent.h"
#include "C_OsmDownloader.h"

#include "C_wxPopupMenu.h"
#include "C_ReportOverview.h"
#include "C_ReportNoVisits.h"
#include "C_ReportNotAssigned.h"
#include "C_ReportAssignementDuration.h"
#include "C_ReportAssignements.h"
#include "C_ReportMapInlet.h"
#include "C_ReportMapCreator.h"
#include "C_ReportMapCreatorAll.h"

class C_wxTmgrMainFrameManager;

/** Implementing C_wxTmgr */
class C_wxTmgrMainFrame : public C_wxTmgr, public wxThreadHelper
{
    friend C_wxTmgrMainFrameManager;

    public:
        /** Constructor */
        C_wxTmgrMainFrame( wxWindow* parent );
        ~C_wxTmgrMainFrame();

    //// end generated class members

    private:
        C_wxTmgrMainFrameManager *MainFrameManager;

        int ActGebId;

        void DoFontChange(void);
        void DoOpenDb(void);

        void OnElementClick(MyFooEvent &event);
        void OnElementUpdated(MyFooEvent &event);
        void OnElementPropUpdated(MyFooEvent &event);
        void OnStartJob(wxCommandEvent &event);

        void OnSizeCategory( wxSizeEvent& event );
        void OntMGRResize( wxSizeEvent& event );
        void OnClose( wxCommandEvent& event );
        void OnOpenDb( wxCommandEvent& event );
        void OnChoiceView( wxCommandEvent& event );
        void OnAbout( wxCommandEvent& event );
        void OnSetAssignee( wxCommandEvent& event );
        void OnCheckBoxExtendNotebook(wxCommandEvent& event);

        void print_console_window(std::string value);
        void show_card(std::string value);

        void monitor_process(void);

        void DoMaperitiveDownloadOsmData(void);
        void DoLaTeXReportOverview(void);
        void DoLaTeXReportAssignementDuration(void);
        void DoLaTeXReportNoVisits(void);
        void DoLaTeXReportNotAssigned(void);
        void DoLaTeXReportAssigned(void);
        void DoCardRender(void);
        void DoLaTeXReportInlet(void);
        void DoCardCreateSet(void);
        void DoLaTeXReportPrintoutSet(void);
        void DoLaTeXReportInfopage(void);
        void DoLaTeXReportBooklet(void);

        int check_sorting(void);

    protected:
        int ProcessType;
        int SortType;
        virtual wxThread::ExitCode Entry();
};

#endif // __C_wxTmgrMainFrame__
