#ifndef __C_wxDlgInfo__
#define __C_wxDlgInfo__

/**
@file
Subclass of InfoDialog, which is generated by wxFormBuilder.
*/

#include "C_wxInfoDialog.h"

//// end generated include

#include "sqlite3.h"
#include "version.h"
#include <boost/version.hpp>
#include "wxIconBundleResLoader.h"
#include "logger.h"
#include "helpers.h"

/** Implementing InfoDialog */
class C_wxDlgInfo : public InfoDialog
{
    public:
        /** Constructor */
        C_wxDlgInfo(wxWindow* parent);
    //// end generated class members

    private:
        void SetImage(void);
        void CollectComponentVersions(void);
        void SetDescriptionText(void);
        void SetChangelogText(void);
        void SetToolchainText(void);
        void SetSVNLogText(void);
        std::string GetResString(const wchar_t *res);

        void OnHtmlLinkClickedChangelog( wxHtmlLinkEvent& event );
        void OnOk(wxCommandEvent &event);

};

#endif // __C_wxDlgInfo__
