#ifndef __C_wxDataListPanel_NoVisits__
#define __C_wxDataListPanel_NoVisits__

/**
@file
Subclass of C_wxDataListPanel, which is generated by wxFormBuilder.
*/

#include "C_wxListPanel.h"
#include "C_Settings.h"
#include "appl_data.h"
#include "C_DbHandle.h"
#include <wx/msgdlg.h>

#include "safe_wx_str.h"

//// end generated include

/** Implementing C_wxDataListPanel */
class C_wxDataListPanel_NoVisits : public C_wxDataListPanel, C_DbHandle
{
    public:
        /** Constructor */
        C_wxDataListPanel_NoVisits( wxWindow* parent );

        void set_settings(ApplicationData* appl_data, C_Settings* settings);
        void show(int geb_id);
        bool SetFont(const wxFont &font);

    private:
        ApplicationData *ad;
        C_Settings *s;

        int m_geb_id;
        int m_last_row_id;
        
        bool m_DSGVO;

        wxVariant get_value(int col, int row);
        void set_value(wxVariant val, int col, int row);

        // Handlers for C_wxDataListPanel events.
        void OnClickAdd( wxCommandEvent& event );
        void OnClickRemove( wxCommandEvent& event );
        void OnEditingDone( wxDataViewEvent& event );


};

#endif // __C_wxDataListPanel_NoVisits__
