SET TOOLS_DRIVE=V:
SET EXT_LIBS_DRIVE=W:
SET PROJ_DRIVE=X:
SET COMPILLER_DRIVE=Z:

SET PATH_TO_TOOLS=C:\CPP\tools
SET PATH_TO_EXT_LIBS=C:\CPP\extlibs
REM SET PATH_TO_COMPILLER=C:\CPP\compiler\i686-8.1.0-release-posix-dwarf-rt_v6-rev0\mingw32
SET PATH_TO_COMPILLER=C:\CPP\compiler\TDM-GCC-64